export const NetworkConstant = {

	ADD_NETWORK_REQUEST: 'ADD_NETWORK_REQUEST',
	ADD_NETWORK_SUCCESS: 'ADD_NETWORK_SUCCESS',
	ADD_NETWORK_FAILURE: 'ADD_NETWORK_FAILURE',

	UPDATE_NETWORK_SUCCESS: 'UPDATE_NETWORK_SUCCESS',
	REMOVE_NETWORK_SUCCESS: 'REMOVE_NETWORK_SUCCESS',

	LIST_NETWORK_REQUEST: 'LIST_NETWORK_REQUEST',
	LIST_NETWORK_SUCCESS: 'LIST_NETWORK_SUCCESS',
	LIST_NETWORK_FAILURE: 'LIST_NETWORK_FAILURE',

	SET_DEFAULT_NETWORK_REQUEST: 'SET_DEFAULT_NETWORK_REQUEST',
	SET_DEFAULT_NETWORK_SUCCESS: 'SET_DEFAULT_NETWORK_SUCCESS',
	SET_DEFAULT_NETWORK_FAILURE: 'SET_DEFAULT_NETWORK_FAILURE',

	GET_DEFAULT_NETWORK_REQUEST: 'GET_DEFAULT_NETWORK_REQUEST',
	GET_DEFAULT_NETWORK_SUCCESS: 'GET_DEFAULT_NETWORK_SUCCESS',
	GET_DEFAULT_NETWORK_FAILURE: 'GET_DEFAULT_NETWORK_FAILURE',
};
