export const CurrencyConstant = {

	LIST_CURRENCY_REQUEST: 'LIST_CURRENCY_REQUEST',
	LIST_CURRENCY_SUCCESS: 'LIST_CURRENCY_SUCCESS',
	LIST_CURRENCY_FAILURE: 'LIST_CURRENCY_FAILURE',

	SET_DEFAULT_CURRENCY_REQUEST: 'SET_DEFAULT_CURRENCY_REQUEST',
	SET_DEFAULT_CURRENCY_SUCCESS: 'SET_DEFAULT_CURRENCY_SUCCESS',
	SET_DEFAULT_CURRENCY_FAILURE: 'SET_DEFAULT_CURRENCY_FAILURE',

	GET_DEFAULT_CURRENCY_REQUEST: 'GET_DEFAULT_CURRENCY_REQUEST',
	GET_DEFAULT_CURRENCY_SUCCESS: 'GET_DEFAULT_CURRENCY_SUCCESS',
	GET_DEFAULT_CURRENCY_FAILURE: 'GET_DEFAULT_CURRENCY_FAILURE',
};
