export const ContactConstant = {

	ADD_CONTACT_REQUEST: 'ADD_CONTACT_REQUEST',
	ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
	ADD_CONTACT_FAILURE: 'ADD_CONTACT_FAILURE',

	UPDATE_CONTACT_REQUEST: 'UPDATE_CONTACT_REQUEST',
	UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
	UPDATE_CONTACT_FAILURE: 'UPDATE_CONTACT_FAILURE',

	REMOVE_CONTACT_REQUEST: 'REMOVE_CONTACT_REQUEST',
	REMOVE_CONTACT_SUCCESS: 'REMOVE_CONTACT_SUCCESS',
	REMOVE_CONTACT_FAILURE: 'REMOVE_CONTACT_FAILURE',

	LIST_CONTACT_REQUEST: 'LIST_CONTACT_REQUEST',
	LIST_CONTACT_SUCCESS: 'LIST_CONTACT_SUCCESS',
	LIST_CONTACT_FAILURE: 'LIST_CONTACT_FAILURE',

};
