export const WalletConstant = {

    ADD_WALLET_REQUEST: 'ADD_WALLET_REQUEST',
    ADD_WALLET_SUCCESS: 'ADD_WALLET_SUCCESS',
    ADD_WALLET_FAILURE: 'ADD_WALLET_FAILURE',

    UPDATE_WALLET_REQUEST: 'UPDATE_WALLET_REQUEST',
    UPDATE_WALLET_SUCCESS: 'UPDATE_WALLET_SUCCESS',
    UPDATE_WALLET_FAILURE: 'UPDATE_WALLET_FAILURE',

    REMOVE_WALLET_REQUEST: 'REMOVE_WALLET_REQUEST',
    REMOVE_WALLET_SUCCESS: 'REMOVE_WALLET_SUCCESS',
    REMOVE_WALLET_FAILURE: 'REMOVE_WALLET_FAILURE',

    LIST_WALLET_REQUEST: 'LIST_WALLET_REQUEST',
    LIST_WALLET_SUCCESS: 'LIST_WALLET_SUCCESS',
    LIST_WALLET_FAILURE: 'LIST_WALLET_FAILURE',

    SET_DEFAULT_WALLET_REQUEST: 'SET_DEFAULT_WALLET_REQUEST',
    SET_DEFAULT_WALLET_SUCCESS: 'SET_DEFAULT_WALLET_SUCCESS',
    SET_DEFAULT_WALLET_FAILURE: 'SET_DEFAULT_WALLET_FAILURE',

    GET_DEFAULT_WALLET_REQUEST: 'GET_DEFAULT_WALLET_REQUEST',
    GET_DEFAULT_WALLET_SUCCESS: 'GET_DEFAULT_WALLET_SUCCESS',
    GET_DEFAULT_WALLET_FAILURE: 'GET_DEFAULT_WALLET_FAILURE',
};
