export const TransactionConstant = {

	ADD_TRANSACTION_REQUEST: 'ADD_TRANSACTION_REQUEST',
	ADD_TRANSACTION_SUCCESS: 'ADD_TRANSACTION_SUCCESS',
	ADD_TRANSACTION_FAILURE: 'ADD_TRANSACTION_FAILURE',

	LIST_TRANSACTION_REQUEST: 'LIST_TRANSACTION_REQUEST',
	LIST_TRANSACTION_SUCCESS: 'LIST_TRANSACTION_SUCCESS',
	LIST_TRANSACTION_FAILURE: 'LIST_TRANSACTION_FAILURE'
};
