export const UserConstant = {

	SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
	SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
	SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

	SIGNIN_REQUEST: 'USERS_SIGNIN_REQUEST',
	SIGNIN_SUCCESS: 'USERS_SIGNIN_SUCCESS',
	SIGNIN_FAILURE: 'USERS_SIGNIN_FAILURE',

	SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
	SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',

	UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
	UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
	UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

	REMEMBER_REQUEST: 'REMEMBER_REQUEST',
	REMEMBER_SUCCESS: 'REMEMBER_SUCCESS',
	REMEMBER_FAILURE: 'REMEMBER_FAILURE',

	CLEAR_REQUEST: 'CLEAR_REQUEST',
	CLEAR_SUCCESS: 'CLEAR_SUCCESS',
	CLEAR_FAILURE: 'CLEAR_FAILURE',
};
